### ISSUE TITLE
all recommendations metrics are seen internally as one metric

### ISSUE THREAD

**Issue by 0xgouda** [cybertec-postgresql/pgwatch#824]
**Describe the bug**
The `Reap()` method in reaper module, assigns all `reco_*` prefixed metrics the `recoMetricName` const name so if 2 or more `reco_*` metrics are present for certain database, they will be seen as the one `recoMetricName` metric and their cancel functions and metric definitions will interfere 
```
if strings.HasPrefix(metric, recoPrefix) {
	metric = recoMetricName
	metricDefExists = true
}
...
dbMetric := monitoredSource.Name + dbMetricJoinStr + metric ### interfere of dbMetric
_, cancelFuncExists := r.cancelFuncs[dbMetric] ### interfere of cancel functions
```

**Steps to reproduce**
1. run pgwatch and update the webui to use any `reco_*` metric with interval > 0
2. in the logs you will see that the metric name is changed to `recommendations` and interval is 0s.
```
2025-06-30 07:45:29.586 [WARNING] [source:books344] [metric:recommendations] Total fetching time of 92.563µs bigger than 0s interval
```

**Comment by pashagolub** [comment]
One shouldn't use `reco_*` metric directly. That was by design. But I agree that this is weird implementation.

**Comment by 0xgouda** [comment]
i looked into it further and i think the above code snippet is trying to default any `reco_*` metric added manually to be `recommendations` metric but since it doesn't modify the sources's `Metric` map the `FetchMetric()` method fails to find an entity for `recommendation` to get `interval` from returning the zero value for `interval` and hence this warning
```
2025-06-30 07:45:29.586 [WARNING] [source:books344] [metric:recommendations] Total fetching time of 92.563µs bigger than 0s interval
```

and also worker keeps getting shutdown due to detected non-existing metric `recommendations` in sources's `Metric` and waked up again and again due to `reco_*` is marked as valid existing metric 
```
2025-07-01 06:15:56.754 [INFO] [source:postgres] [metric:recommendations] [interval:10] starting gatherer
2025-07-01 06:15:56.754 [INFO] [source:postgres] [metric:recommendations] stopping gatherer...
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:486ns] Acquire
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:373ns] Acquire
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:165ns] Acquire
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:168ns] Acquire ### QueryMeausrements() failure
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:151ns] Acquire
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:151ns] Acquire
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:156ns] Acquire
2025-07-01 06:15:56.754 [ERROR] [err:context canceled] [time:153ns] Acquire
2025-07-01 06:15:56.754 [INFO] [source:postgres] [metric:recommendations] [rows:1] [cache:false] measurements 
....
``` 

i think the simplest approach is to update the above code to `continue` and hence skip any `reco_*` added manually.

instead of going through updating the source's `Metric` to switch any `reco_*` to `recommendations` because my initial estimation for this is that we gonna need RWLock on each Sources 's Metric map to be able to update it concurrently on detecting `reco_*`

**Comment by pashagolub** [comment]
Some history intro. Recommendation metrics are one of the oldest. That means when they were introduced there was no functionality to specify what exactly storage name to use, e.g.

```yaml
    db_size_approx:
        description: >
            Retrieves an approximate size of the current database and the size of the `pg_catalog` schema, providing insights into the storage usage of the database.
            It returns the size in bytes for both the current database and the catalog schema.
            This metric helps administrators monitor database size and storage consumption.
        sqls:
            11: ...
        gauges:
            - '*'
        metric_storage_name: db_size
```

Nowadays, this would be the proper and much better way to deal with different recommendations. Just define different `reco_foo` metrics and use `metric_storage_name: recommendations`. 
This way user receives extreme flexibility! They can choose what exactly recommendations to run, what exactly intervals for each of them, to create custom presets and so on, and so on...

Now, this is doable and this what I will implement in the nearest future. Mostly because of #764 where we observe tremendous memory consumption in high loaded environments.

That means I wouldn't touch anything right now and trying to apply some fixes. We need to assume that it's forbidden to use any `reco_*` metric directly.
